config/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),

]

urlpatterns += i18n_patterns(

    path('', include('src.main.urls', namespace='main')),
    path('adminlte/', include('src.core.adminlte.urls', namespace='adminlte')),
    path('user/', include('src.user.urls', namespace='user')),
    path('auth/', include('src.authentication.urls', namespace='auth')),
    path('cms/', include('src.cms.urls', namespace='cms')),
    prefix_default_language=True
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/adminlte/urls.py
from django.urls import path
from .views import (banners_top_update, film_list, banners_edit, news_and_actions_update,
                    through_banner_update, users_list, user_edit, user_delete, pages,
                    main_page, page_add, page_edit, page_delete,
                    edit_mainpage, add_movie, edit_movie, delete_movie, cinemas_list,
                    cinema_add, contacts, edit_cinema, delete_cinema, hall_add,
                    hall_edit, hall_delete, news_and_actions_add,
                    news_and_actions, news_and_actions_edit, news_and_actions_delete,
                    mailing, mailing_users_view, delete_template, dashboard_stats,
                    edit_schedule, schedule_list, add_schedule, delete_schedule)
from django.conf import settings
from django.conf.urls.static import static


app_name = 'adminlte'

urlpatterns = [
    path('', dashboard_stats, name='statistics'),
    path('bannersandsliders/', banners_edit, name='banners'),
    path('banners/top/update/', banners_top_update, name='banners_top_update'),
    path('banners/news/update/', news_and_actions_update, name='news_banner_update'),
    path('baneers/through/update/', through_banner_update, name='banners_through_update'),
    path('films/', film_list, name='film_list'),
    path('films/add/', add_movie, name='add_movie'),
    path('films/edit/<int:pk>/', edit_movie, name='edit_movie'),
    path('film/delete/<int:pk>/', delete_movie, name='delete_film'),
    path('users/', users_list, name='users_list'),
    path('users/edit/<int:pk>/', user_edit, name='user_edit'),
    path('users/delete/<int:pk>/', user_delete, name='user_delete'),
    path('pages/', pages, name='pages'),
    path('pages/mainpage', main_page, name='main_page'),
    path('page/add', page_add, name='add_page'),
    path('page/edit/<int:pk>/', page_edit, name='edit_page'),
    path('page/delete/<int:pk>/', page_delete, name='delete_page'),
    path('page/mainpage/edit', edit_mainpage, name='edit_mainpage'),
    path('page/contacts/edit', contacts, name='contacts'),
    path('cinemas/', cinemas_list, name='cinemas_list'),
    path('cinemas/add/', cinema_add, name='cinema_add'),
    path('cinemas/edit/<int:pk>', edit_cinema, name='edit_cinema'),
    path('cinemas/delete/<int:pk>', delete_cinema, name='cinema_delete'),
    path('cinemas/hall/add/<int:cinema_pk>', hall_add, name='hall_add'),
    path('cinemas/hall/edit/<int:cinema_pk>/<int:pk>', hall_edit, name='hall_edit'),
    path('cinemas/hall/delete/<int:cinema_pk>/<int:pk>', hall_delete, name='hall_delete'),
    path('news_and_actions/<int:is_news>/', news_and_actions, name='news_and_actions'),
    path('news_and_actions/add/<int:is_news>', news_and_actions_add, name='news_and_actions_add'),
    path('news_and_actions/edit/<int:pk>/', news_and_actions_edit, name='news_and_actions_edit'),
    path('news_and_actions/delete/<int:pk>/', news_and_actions_delete, name='news_and_actions_delete'),
    path('mailing/', mailing, name="mailing"),
    path('mailing/users/<int:mailing_id>/', mailing_users_view, name='mailing_users'),
    path('mailing/delete/<int:pk>/', delete_template, name='delete_template'),
    path('schedule/list', schedule_list, name='schedule_list'),
    path('schedule/edit/<int:pk>/', edit_schedule, name='edit_schedule'),
    path('schedule/add/', add_schedule, name='schedule_add'),
    path('schedule/delete/<int:pk>/', delete_schedule, name='delete_schedule'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/urls.py
from django.urls import path
from .views import main_page, poster, booking, schedule, news_page, actions_page, new_and_action, page, poster_coming_soon, filter_schedule, get_halls

app_name = 'main'

urlpatterns = [
    path('', main_page, name='main_page'),
    path('poster/', poster, name='poster'),
    path('poster/comingsoon', poster_coming_soon, name='poster_coming_soon'),
    path('filter-schedule/', filter_schedule, name='filter_schedule'),
    path('get-halls/', get_halls, name='get_halls'),
    path('booking/<int:schedule_id>', booking, name='booking'),
    path('schedule/', schedule, name='schedule_page'),
    path('news/', news_page, name='news_page'),
    path('actions/', actions_page, name='actions_page'),
    path('news_actions/<int:item_pk>', new_and_action, name='new_and_action_page'),
    path('page/<int:page_id>', page, name='page'),

]

src/core/adminlte/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.contrib import messages
from src.cms.models import BannerComponent, ThroughBanner, Contacts, Hall
from src.user.models import User
from src.main.models import DailyStats
from django.contrib.auth import get_user_model
from src.authentication.forms import UserUpdateForm
from django.core.paginator import Paginator
from django.db.models import Q
from django.utils import timezone
from .tasks import send_mass_mail_task
import datetime
import json
from django.db.models import Count
from django.contrib.auth.decorators import user_passes_test

@user_passes_test(lambda u: u.is_superuser)
def banners_edit(request):
    banner_top = Banner.objects.order_by('pk').filter(is_promo=True).first()
    if banner_top is None:
        banner_top = Banner.objects.create(speed=5, is_active=True, is_promo=True)

    banner_news = Banner.objects.order_by('pk').filter(is_promo=False).first()
    if banner_news is None:
        banner_news = Banner.objects.create(speed=5, is_active=True, is_promo=False)

    banner_through = ThroughBanner.objects.first()
    if banner_through is None:
        banner_through = ThroughBanner.objects.create(is_active=True, background="#FFFFFF")

    form_top = BannerForm(instance=banner_top, prefix="top_main")
    formset_top = BannerComponentFormSet(queryset=banner_top.banner_component.all(), prefix='top_items')

    form_news = BannerForm(instance=banner_news, prefix="news_main")
    formset_news = BannerComponentFormSet(queryset=banner_news.banner_component.all(), prefix='news_items')

    form_through = ThroughBannerForm(instance=banner_through, prefix="through_main")

    formset_through = ThroughBannerFormSet(
        queryset=banner_through.banner_component.all(),
        prefix='through_items'
    )

    return render(request, "adminlte/banners_edit.html", {
        "form_top": form_top,
        "formset_top": formset_top,
        "form_news": form_news,
        "formset_news": formset_news,

        "form_through": form_through,
        "formset_through": formset_through,
    })

@user_passes_test(lambda u: u.is_superuser)
def through_banner_update(request):
    banner = ThroughBanner.objects.first()
    if not banner:
        banner = ThroughBanner.objects.create(is_active=True, background="#FFFFFF")

    if request.method == "POST":
        form = ThroughBannerForm(request.POST, instance=banner, prefix="through_main")

        formset = ThroughBannerFormSet(
            request.POST, request.FILES,
            queryset=banner.banner_component.all(),
            prefix="through_items"
        )

        if form.is_valid() and formset.is_valid():
            banner_instance = form.save()

            instances = formset.save(commit=False)
            for comp in instances:
                comp.save()
                banner_instance.banner_component.clear()
                banner_instance.banner_component.add(comp)

            return redirect("adminlte:banners")
        else:
            print("Through Banner Errors:", form.errors, formset.errors)

    else:
        form = ThroughBannerForm(instance=banner, prefix="through_main")
        formset = ThroughBannerFormSet(
            queryset=banner.banner_component.all(),
            prefix="through_items"
        )

    return render(request, "adminlte/through_banner_edit.html", {
        "form_through": form,
        "formset_through": formset,
    })

@user_passes_test(lambda u: u.is_superuser)
def banners_top_update(request):
    banner = Banner.objects.order_by('pk').filter(is_promo=True).first()
    if not banner:
        banner = Banner.objects.create(speed=5, is_active=True, is_promo=True)

    if request.method == "POST":
        form = BannerForm(request.POST, instance=banner, prefix="top_main")
        formset = BannerComponentFormSet(
            request.POST, request.FILES,
            queryset=banner.banner_component.all(),
            prefix="top_items"
        )

        if form.is_valid() and formset.is_valid():
            banner_instance = form.save()

            for f in formset.deleted_forms:
                comp = f.instance
                if comp.pk:
                    banner_instance.banner_component.remove(comp)

                    comp.delete()

            instances = formset.save(commit=False)
            for comp in instances:
                comp.save()
                banner_instance.banner_component.add(comp)

            return redirect("adminlte:banners")
        else:
            print("TOP Errors:", form.errors, formset.errors)

    return redirect("adminlte:banners")

@user_passes_test(lambda u: u.is_superuser)
def news_and_actions_update(request):
    banner = Banner.objects.order_by('pk').filter(is_promo=False).first()
    if not banner:
        banner = Banner.objects.create(speed=5, is_active=True, is_promo=False)

    if request.method == "POST":
        form = BannerForm(request.POST, instance=banner, prefix="news_main")
        formset = BannerComponentFormSet(
            request.POST, request.FILES,
            queryset=banner.banner_component.all(),
            prefix="news_items"
        )

        if form.is_valid() and formset.is_valid():
            banner_instance = form.save()

            for f in formset.deleted_forms:
                comp = f.instance
                if comp.pk:
                    banner_instance.banner_component.remove(comp)
                    comp.delete()

            instances = formset.save(commit=False)
            for comp in instances:
                comp.save()
                banner_instance.banner_component.add(comp)

            return redirect("adminlte:banners")
        else:
             print("NEWS Errors:", form.errors, formset.errors)

    return redirect("adminlte:banners")

@user_passes_test(lambda u: u.is_superuser)
def film_list(request):
    now = timezone.now()

    current_movies = Movie.objects.filter(date_of_show__lte=now).order_by('-date_of_show')
    soon_movies = Movie.objects.filter(date_of_show__gt=now).order_by('date_of_show')

    contex = {
        'current_movies': current_movies,
        'soon_movies': soon_movies,
    }

    return render(request, 'adminlte/film_list.html', contex)


User = get_user_model()

@user_passes_test(lambda u: u.is_superuser)
def user_edit(request, pk):
    user_obj = get_object_or_404(User, pk=pk)

    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=user_obj)
        if form.is_valid():
            form.save()
            messages.success(request, f'Користувача {user_obj.username} оновлено!')
            return redirect('adminlte:users_list')
    else:
        form = UserUpdateForm(instance=user_obj)

    context = {
        'form': form,
        'user_obj': user_obj
    }
    return render(request, 'adminlte/user_edit.html', context)

@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    user_obj = get_object_or_404(User, pk=pk)

    if request.method == "POST":
        username = user_obj.username
        user_obj.delete()
        messages.warning(request, f'Користувача {username} видалено.')
        return redirect('adminlte:users_list')

    return redirect('adminlte:users_list')

@user_passes_test(lambda u: u.is_superuser)
def users_list(request):
    queryset = User.objects.all().order_by('-date_joined')

    search_query = request.GET.get('q')

    if search_query:
        queryset = queryset.filter(
            Q(username__icontains=search_query) |
            Q(email__icontains=search_query) |
            Q(first_name__icontains=search_query) |
            Q(last_name__icontains=search_query)
        )

    paginator = Paginator(queryset, 10)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'users': page_obj,
        'page_obj': page_obj,
        'is_paginated': page_obj.has_other_pages(),
    }

    return render(request, 'adminlte/users_list.html', context)

@user_passes_test(lambda u: u.is_superuser)
def main_page(request):
    main_page_obj, created = MainPage.objects.get_or_create(id=1)

    if not main_page_obj.seo_block:
        seo_block_obj = SeoBlock.objects.create()
        main_page_obj.seo_block = seo_block_obj
        main_page_obj.save()
    else:
        seo_block_obj = main_page_obj.seo_block

    if request.method == 'POST':
        main_form = MainPageForm(request.POST, instance=main_page_obj)
        seo_form = SeoBlockForm(request.POST, instance=seo_block_obj)

        if main_form.is_valid() and seo_form.is_valid():
            main_form.save()
            seo_form.save()
            return redirect('adminlte:main_page')
    else:
        main_form = MainPageForm(instance=main_page_obj)
        seo_form = SeoBlockForm(instance=seo_block_obj)

    context = {
        'main_form': main_form,
        'seo_form': seo_form,
    }
    return render(request, 'adminlte/main_page.html', context)


@user_passes_test(lambda u: u.is_superuser)
def pages(request):
    main_page = MainPage.load()
    contacts = Contacts.load()
    pages = Page.objects.all().order_by('id')
    context = {
        "main_page": main_page,
        "pages": pages,
        "contacts": contacts,
    }

    return render(request, 'adminlte/pages.html', context)

@user_passes_test(lambda u: u.is_superuser)
def page_add(request):

    if request.method == 'POST':

        page_form = PageForm(request.POST, request.FILES)
        seo_form = SeoBlockForm(request.POST)

        gallery_formset = GalleryFormSet(
            request.POST,
            request.FILES,
            queryset=Gallery.objects.none(),
            prefix='gallery',
        )

        if page_form.is_valid() and seo_form.is_valid() and gallery_formset.is_valid():
            seo_block = seo_form.save()
            page = page_form.save(commit=False)
            page.seo_block = seo_block
            page.save()

src/core/adminlte/templates/adminlte/cinemas.html
{% extends 'admin_base.html' %}
{% load static %}

{% block content %}

<style>
    .cinema-card {
        position: relative;
        transition: transform 0.2s;
        border: 1px solid #dee2e6;
        background: #fff;
    }
    .cinema-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 4px 15px rgba(0,0,0,0.1);
    }

    .cinema-logo-placeholder {
        background-color: #ffffff;
        height: 180px;
        display: flex;
        align-items: center;
        justify-content: center;
        overflow: hidden;
        border-bottom: 1px solid #f0f0f0;
        padding: 10px;
    }

    .cinema-logo-placeholder img {
        width: 100%;
        height: 100%;
        object-fit: contain;
    }

    .cinema-logo-placeholder i {
        font-size: 4rem;
        color: #dee2e6;
    }

    /* Стилі кнопки */
    .btn-delete-cinema {
        position: absolute;
        top: -10px;
        right: -10px;
        background: #ffcccc;
        color: red;
        border-radius: 50%;
        width: 30px;
        height: 30px;
        display: flex;
        align-items: center;
        justify-content: center;
        border: 1px solid red;
        z-index: 10;
        font-weight: bold;
        line-height: 1;
        cursor: pointer;
        padding: 0;
    }
    .btn-delete-cinema:hover {
        background: red;
        color: white;
    }
</style>

<div class="container-fluid mt-4">

    <div class="d-flex justify-content-center align-items-center flex-column mb-5">
        <h3 class="fw-bold mb-3">Список кінотеатрів</h3>

        <a href="{% url 'adminlte:cinema_add' %}" class="btn btn-primary rounded-pill px-4">
            <i class="bi bi-plus-lg"></i> Додати кінотеатр
        </a>
    </div>

    <div class="row">
        {% for cinema in cinemas %}
        <div class="col-6 col-md-4 col-lg-3 mb-4">

            <div class="card cinema-card h-100">

                <form action="{% url 'adminlte:cinema_delete' pk=cinema.pk %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn-delete-cinema"
                            onclick="return confirm('Ви дійсно хочете видалити кінотеатр {{ cinema.title }}?');">
                        x
                    </button>
                </form>

                <a href="{% url 'adminlte:edit_cinema' pk=cinema.pk %}" class="text-decoration-none text-dark h-100 d-flex flex-column">

                    <div class="cinema-logo-placeholder">
                        {% if cinema.main_image %}
                            <img src="{{ cinema.main_image.url }}" alt="{{ cinema.title }}">
                        {% else %}
                            <i class="bi bi-building"></i>
                        {% endif %}
                    </div>

                    <div class="card-body text-center flex-grow-1 d-flex flex-column justify-content-center">
                        <h5 class="card-title fw-bold mb-1">{{ cinema.title }}</h5>
                        <p class="card-text text-muted small mb-0">{{ cinema.city }}</p>
                    </div>
                </a>

            </div>

        </div>
        {% empty %}
        <div class="col-12 text-center text-muted mt-5">
            <h4>Список порожній</h4>
        </div>
        {% endfor %}
    </div>

</div>

{% endblock %}

src/core/adminlte/templates/adminlte/film_list.html
{% extends 'admin_base.html' %}
{% load static %}

{% block content %}

<style>
    .movie-card {
        position: relative;
        transition: transform 0.2s;
    }
    .movie-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
    }

    .movie-img-placeholder {
        background-color: #e9ecef;
        height: 200px;
        display: flex;
        align-items: center;
        justify-content: center;
        border-radius: 4px;
        overflow: hidden;
    }

    .movie-img-placeholder img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }

    .movie-img-placeholder i {
        font-size: 3rem;
        color: #adb5bd;
    }

    .btn-delete-movie {
        position: absolute;
        top: -10px;
        right: -10px;
        background: #ffcccc;
        color: red;
        border-radius: 50%;
        width: 25px;
        height: 25px;
        display: flex;
        align-items: center;
        justify-content: center;
        text-decoration: none;
        border: 1px solid red;
        z-index: 10;
        font-weight: bold;
        font-size: 14px;
        line-height: 1;
    }
    .btn-delete-movie:hover {
        background: red;
        color: white;
    }
</style>


    <a href="{% url 'adminlte:add_movie' %}" class="btn btn-primary rounded-pill px-3">
        <i class="bi bi-plus-lg"></i> Додати новий фільм
    </a>
    <br> <br>

    <div class="container-fluid mt-4">

        <h4 class="text-center fw-bold mb-4">Список поточних фільмів</h4>

        <div class="row text-center" id="current-movies-list">
            {% for movie in current_movies %}
            <div class="col-6 col-md-4 col-lg-2 mb-4">

                <div class="card border-0 movie-card h-100">

    <button type="button" class="btn-delete-movie" data-bs-toggle="modal" data-bs-target="#deleteModal{{ movie.id }}">
        x
    </button>

    <a href="{% url 'adminlte:edit_movie' pk=movie.pk %}" class="text-decoration-none text-dark h-100">

        <div class="movie-img-placeholder mb-2">
            {% if movie.main_image %}
                <img src="{{ movie.main_image.url }}" alt="{{ movie.title }}">
            {% else %}
                <i class="bi bi-image"></i>
            {% endif %}
        </div>

        <div class="fw-bold small text-center">
            {{ movie.title }}
        </div>

        {% if movie.date_of_show %}
        <div class="small text-muted text-center">
            {{ movie.date_of_show|date:"d.m.Y" }}
        </div>
        {% endif %}

    </a>

</div>

                <div class="modal fade" id="deleteModal{{ movie.id }}" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Видалити фільм?</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body text-start">
                                Ви впевнені, що хочете видалити <strong>"{{ movie.title }}"</strong>?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Ні</button>
                                <a href="{% url 'adminlte:delete_film' pk=movie.id %}" class="btn btn-danger">Так, видалити</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            {% empty %}
            <div class="col-12 text-muted">Немає фільмів</div>
            {% endfor %}
        </div>

        <h4 class="text-center fw-bold mb-4 mt-5">Список фильмів, які покажуть скоро</h4>

        <div class="row text-center" id="soon-movies-list">
            {% for movie in soon_movies %}
            <div class="col-6 col-md-4 col-lg-2 mb-4">
                <div class="card border-0 movie-card h-100">

                    <button type="button" class="btn-delete-movie" data-bs-toggle="modal" data-bs-target="#deleteModalSoon{{ movie.id }}">
                        x
                    </button>
                <a href="{% url 'adminlte:edit_movie' pk=movie.pk %}" class="text-decoration-none text-dark h-100">

                    <div class="movie-img-placeholder mb-2">
                        {% if movie.main_image %}
                            <img src="{{ movie.main_image.url }}">
                        {% else %}
                            <i class="bi bi-image"></i>
                        {% endif %}
                    </div>

                    <div class="fw-bold small text-dark">
                        {{ movie.title }}
                    </div>
                    <div class="small text-muted">{{ movie.date_of_show|date:"d.m.Y" }}</div>
                </a>
                </div>

                 <div class="modal fade" id="deleteModalSoon{{ movie.id }}" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Видалити фільм?</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body text-start">
                                Ви впевнені, що хочете видалити <strong>"{{ movie.title }}"</strong>?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Ні</button>
                                <a href="{% url 'adminlte:delete_film' pk=movie.id %}" class="btn btn-danger">Так, видалити</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            {% empty %}
             <div class="col-12 text-muted">Немає фільмів</div>
            {% endfor %}
        </div>

    </div>

{% endblock %}

src/core/adminlte/templates/adminlte/news_and_actions.html
{% extends 'admin_base.html' %}
{% load static %}

{% block content %}

    <style>
    .btn-action {
        border: none;
        background: transparent;
        cursor: pointer;
        font-size: 1.2rem;
        padding: 0 5px;
        transition: color 0.2s;
    }

    .btn-edit { color: #555; text-decoration: none; }
    .btn-edit:hover { color: #0056b3; }

    .btn-delete { color: #555; }
    .btn-delete:hover { color: #dc3545; }
</style>

    <a href="{% url 'adminlte:news_and_actions_add' is_news=is_news|yesno:"1,0" %}" class="btn btn-primary rounded-pill px-3">
    <i class="bi bi-plus-lg"></i>

        {% if is_news  %}
            Додати нову новину
        {% else %}
            Додати нову акцію
        {% endif %}
    </a>
    <br> <br>
<table class="table table-striped align-middle"> <thead>
    <tr>
      <th scope="col">Назва</th>
      <th scope="col">Дата оновлення</th>
      <th scope="col">Статус</th>
      <th scope="col" style="width: 100px;">Дії</th>
    </tr>
  </thead>
  <tbody>

    {% for item in items %}

    <tr>
      <td>{{ item.title }}</td>
      <td>{{ item.updated_at }}</td>
      <td>{{ item.is_active }}</td>

      <td>
          <a href="{% url 'adminlte:news_and_actions_edit' pk=item.id %}" class="btn-action btn-edit" title="Редагувати">&#9998;</a>

          <form action="{% url 'adminlte:news_and_actions_delete' pk=item.pk %}" method="POST" style="display:inline;">
             {% csrf_token %} <button type="submit" class="btn-action btn-delete" title="Видалити" onclick="return confirm('Ви впевнені?')">
                    &#128465;
             </button>
          </form>
      </td>
    </tr>

  {% endfor %}
  </tbody>
</table>
{% endblock %}

src/core/adminlte/templates/adminlte/schedule_list.html
{% extends 'admin_base.html' %}
{% load static %}

{% block content %}

<div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1>Розклад сеансів</h1>
        </div>
        <div class="col-sm-6 text-right">
            <a href="{% url 'adminlte:schedule_add' %}" class="btn btn-success">
                <i class="fas fa-plus"></i> Додати сеанс
            </a>
        </div>
    </div>
</div>


<section class="content">
    <div class="container-fluid">
        <div class="card card-outline card-primary">
            <div class="card-header">
                <h3 class="card-title">Усі заплановані покази</h3>
            </div>
            <div class="card-body">
                <table id="scheduleTable" class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Дата та час</th>
                            <th>Фільм</th>
                            <th>Кінотеатр</th>
                            <th>Зал</th>
                            <th>Ціна (грн)</th>
                            <th style="width: 120px;">Дії</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in schedules %}
                        <tr>
                            <td>{{ item.date|date:"d.m.Y H:i" }}</td>
                            <td><strong>{{ item.id_movie.title }}</strong></td>
                            <td>{{ item.id_cinema.title }}</td>
                            <td><span class="badge badge-info">{{ item.id_hall.number }}</span></td>
                            <td>{{ item.price }} ₴</td>
                            <td class="text-center">
                                <div class="btn-group">
    <a href="{% url 'adminlte:edit_schedule' item.pk %}" class="btn btn-sm btn-info shadow-sm">
        <i class="fas fa-pencil-alt"></i> Редагувати
    </a>
    <a href="{% url 'adminlte:delete_schedule' item.pk %}" class="btn btn-sm btn-danger shadow-sm">
        <i class="fas fa-pencil-alt"></i> Видалити
    </a>
</div>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="6" class="text-center">Розклад поки порожній.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block extra_js %}
<script>
  $(function () {
    $("#scheduleTable").DataTable({
      "responsive": true,
      "lengthChange": true,
      "autoWidth": false,
      "language": {
          "url": "//cdn.datatables.net/plug-ins/1.13.4/i18n/uk.json"
      },
      "order": [[0, "desc"]]
    });

    $('.delete-btn').on('click', function() {
        const id = $(this).data('id');
        if (confirm('Ви впевнені, що хочете видалити цей сеанс?')) {
            window.location.href = `/admin/schedule/delete/${id}/`;
        }
    });
  });
</script>
{% endblock %}