config/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),

]

urlpatterns += i18n_patterns(

    path('', include('src.main.urls', namespace='main')),
    path('adminlte/', include('src.core.adminlte.urls', namespace='adminlte')),
    path('user/', include('src.user.urls', namespace='user')),
    path('auth/', include('src.authentication.urls', namespace='auth')),
    path('cms/', include('src.cms.urls', namespace='cms')),
    prefix_default_language=True
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/authentication/urls.py
from django.urls import path
from .views import login_user, register, profile, logout_user
from django.conf.urls.static import static
from django.conf import settings

app_name = 'authentication'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout_user, name='logout'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/cms/urls.py
from django.urls import path
from .views import cinema_page, cinemas_list, hall_page, contacts_list

app_name = 'cinema'

urlpatterns = [
    path('cinemas', cinemas_list, name='cinemas_list'),
    path('cinema/<int:cinema_id>/', cinema_page, name="cinema_page"),
    path('hall/<int:hall_id>', hall_page, name="hall_page"),
    path('contacts', contacts_list, name='contacts_list'),
]

src/core/adminlte/urls.py
from django.urls import path
from .views import (banners_top_update, film_list, banners_edit, news_and_actions_update,
                    through_banner_update, users_list, user_edit, user_delete, pages,
                    main_page, page_add, page_edit, page_delete,
                    edit_mainpage, add_movie, edit_movie, delete_movie, cinemas_list,
                    cinema_add, contacts, edit_cinema, delete_cinema, hall_add,
                    hall_edit, hall_delete, news_and_actions_add,
                    news_and_actions, news_and_actions_edit, news_and_actions_delete,
                    mailing, mailing_users_view, delete_template, dashboard_stats,
                    edit_schedule, schedule_list, add_schedule, delete_schedule)
from django.conf import settings
from django.conf.urls.static import static


app_name = 'adminlte'

urlpatterns = [
    path('', dashboard_stats, name='statistics'),
    path('bannersandsliders/', banners_edit, name='banners'),
    path('banners/top/update/', banners_top_update, name='banners_top_update'),
    path('banners/news/update/', news_and_actions_update, name='news_banner_update'),
    path('baneers/through/update/', through_banner_update, name='banners_through_update'),
    path('films/', film_list, name='film_list'),
    path('films/add/', add_movie, name='add_movie'),
    path('films/edit/<int:pk>/', edit_movie, name='edit_movie'),
    path('film/delete/<int:pk>/', delete_movie, name='delete_film'),
    path('users/', users_list, name='users_list'),
    path('users/edit/<int:pk>/', user_edit, name='user_edit'),
    path('users/delete/<int:pk>/', user_delete, name='user_delete'),
    path('pages/', pages, name='pages'),
    path('pages/mainpage', main_page, name='main_page'),
    path('page/add', page_add, name='add_page'),
    path('page/edit/<int:pk>/', page_edit, name='edit_page'),
    path('page/delete/<int:pk>/', page_delete, name='delete_page'),
    path('page/mainpage/edit', edit_mainpage, name='edit_mainpage'),
    path('page/contacts/edit', contacts, name='contacts'),
    path('cinemas/', cinemas_list, name='cinemas_list'),
    path('cinemas/add/', cinema_add, name='cinema_add'),
    path('cinemas/edit/<int:pk>', edit_cinema, name='edit_cinema'),
    path('cinemas/delete/<int:pk>', delete_cinema, name='cinema_delete'),
    path('cinemas/hall/add/<int:cinema_pk>', hall_add, name='hall_add'),
    path('cinemas/hall/edit/<int:cinema_pk>/<int:pk>', hall_edit, name='hall_edit'),
    path('cinemas/hall/delete/<int:cinema_pk>/<int:pk>', hall_delete, name='hall_delete'),
    path('news_and_actions/<int:is_news>/', news_and_actions, name='news_and_actions'),
    path('news_and_actions/add/<int:is_news>', news_and_actions_add, name='news_and_actions_add'),
    path('news_and_actions/edit/<int:pk>/', news_and_actions_edit, name='news_and_actions_edit'),
    path('news_and_actions/delete/<int:pk>/', news_and_actions_delete, name='news_and_actions_delete'),
    path('mailing/', mailing, name="mailing"),
    path('mailing/users/<int:mailing_id>/', mailing_users_view, name='mailing_users'),
    path('mailing/delete/<int:pk>/', delete_template, name='delete_template'),
    path('schedule/list', schedule_list, name='schedule_list'),
    path('schedule/edit/<int:pk>/', edit_schedule, name='edit_schedule'),
    path('schedule/add/', add_schedule, name='schedule_add'),
    path('schedule/delete/<int:pk>/', delete_schedule, name='delete_schedule'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/urls.py
from django.urls import path
from .views import main_page, poster, booking, schedule, news_page, actions_page, new_and_action, page, poster_coming_soon, filter_schedule, get_halls

app_name = 'main'

urlpatterns = [
    path('', main_page, name='main_page'),
    path('poster/', poster, name='poster'),
    path('poster/comingsoon', poster_coming_soon, name='poster_coming_soon'),
    path('filter-schedule/', filter_schedule, name='filter_schedule'),
    path('get-halls/', get_halls, name='get_halls'),
    path('booking/<int:schedule_id>', booking, name='booking'),
    path('schedule/', schedule, name='schedule_page'),
    path('news/', news_page, name='news_page'),
    path('actions/', actions_page, name='actions_page'),
    path('news_actions/<int:item_pk>', new_and_action, name='new_and_action_page'),
    path('page/<int:page_id>', page, name='page'),

]

templates/admin_base.html
{% load static %}
<!DOCTYPE html>
<html lang="uk">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{% block title %}Адмінка{% endblock %}</title>

  <link rel="stylesheet" href="{% static 'css/fonts.css' %}">

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-icons.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/overlayscrollbars.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/adminlte.css' %}">

  {% block extra_css %}{% endblock %}
</head>

<body class="layout-fixed sidebar-expand-lg bg-body-tertiary">
  <div class="app-wrapper">
    <nav class="app-header navbar navbar-expand bg-body">
      <div class="container-fluid">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" data-lte-toggle="sidebar" href="#" role="button">
              <i class="bi bi-list"></i>
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <aside class="app-sidebar bg-body-secondary shadow" data-bs-theme="dark">
      <div class="sidebar-wrapper">
         <ul class="nav sidebar-menu flex-column d-flex h-100" data-lte-toggle="treeview" role="menu">
          <li class="nav-item">
            <a href="{% url 'adminlte:statistics' %}" class="nav-link">
              <i class="nav-icon bi bi-speedometer2"></i>
              <p>Статистика</p>
            </a>
          </li>

           <li class="nav-item">
            <a href="{% url 'adminlte:banners' %}" class="nav-link">
              <i class="nav-icon bi bi-speedometer2"></i>
              <p>Банери/Слайдери</p>
            </a>
          </li>

         <li class="nav-item">
            <a href="{% url 'adminlte:film_list' %}" class="nav-link">
              <i class="nav-icon bi bi-calendar-event"></i>
              <p>Фільми</p>
            </a>
          </li>

          <li class="nav-item">
            <a href="{% url 'adminlte:cinemas_list' %}" class="nav-link">
              <i class="nav-icon bi bi-calendar-event"></i>
              <p>Кінотеатри</p>
            </a>
          </li>

          <li class="nav-item">
            <a href="{% url 'adminlte:news_and_actions' is_news=1 %}" class="nav-link">
              <i class="nav-icon bi bi-grid-3x3-gap"></i>
              <p>Новини</p>
            </a>
          </li>

          <li class="nav-item">
            <a href="{% url 'adminlte:news_and_actions' is_news=0 %}" class="nav-link">
              <i class="nav-icon bi bi-cup-hot"></i>
              <p>Акції</p>
            </a>
          </li>

           <li class="nav-item">
            <a href="{% url 'adminlte:pages' %}" class="nav-link">
              <i class="nav-icon bi bi-cup-hot"></i>
              <p>Сторінки</p>
            </a>
          </li>


          <li class="nav-item">
            <a href="{% url 'adminlte:schedule_list' %}" class="nav-link">
              <i class="nav-icon bi bi-calendar-event"></i>
              <p>Керування розкладом</p>
            </a>
          </li>

           <li class="nav-item">
            <a href="{% url 'adminlte:users_list' %}" class="nav-link">
              <i class="nav-icon bi bi-cup-hot"></i>
              <p>Користувачі</p>
            </a>
          </li>

           <li class="nav-item">
            <a href="{% url 'adminlte:mailing' %}" class="nav-link">
              <i class="nav-icon bi bi-cup-hot"></i>
              <p>Розсилання</p>
            </a>
          </li>


         <li class="nav-item" style="margin-top: auto">
             <a href="{% url 'main:main_page' %}" class="nav-link">
             <i class="bi bi-box-arrow-left"></i>
             <p>Назад на головну</p>
             </a>
         </li>
        </ul>
      </div>
    </aside>

    <main class="app-main">
      <div class="app-content pt-3 px-3">
        {% block content %}{% endblock %}
      </div>
    </main>
  </div>

  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

  <script src="{% static 'js/overlayscrollbars.browser.es6.min.js' %}"></script>

  <script src="{% static 'js/adminlte.js' %}"></script>

  <script>
    document.addEventListener('DOMContentLoaded', () => {
      const el = document.querySelector('.sidebar-wrapper');
      if (el && window.OverlayScrollbarsGlobal) {
        OverlayScrollbarsGlobal.OverlayScrollbars(el, {
          scrollbars: { autoHide: 'leave' }
        });
      }
    });
  </script>

  {% block extra_js %}{% endblock %}
</body>
</html>

templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
{% get_current_language as CURRENT_LANG %}
<html lang="{{ CURRENT_LANG }}">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}KinoCMS{% endblock %}</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/headers.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.min.css' %}">
</head>

<body>
    <header class="d-flex flex-wrap align-items-center justify-content-between py-3 mb-4 border-bottom bg-dark text-white px-3">

        <div class="d-flex align-items-center">
            <a href="{% url 'main:main_page' %}" class="d-inline-flex text-decoration-none text-white me-4 align-items-center">
                <img src="{% static 'img/logo.png' %}" alt="logo" width="35" height="35" class="me-2">
                <span class="fs-4 fw-bold">KinoCMS</span>
            </a>

            <ul class="nav mb-0">
                <li><a href="{% url 'main:main_page' %}" class="nav-link px-2 text-white fw-bold">{% trans "Головна" %}</a></li>
                <li><a href="{% url 'main:poster' %}" class="nav-link px-2 text-white-50">{% trans "Афіша" %}</a></li>
                <li><a href="{% url 'main:schedule_page' %}" class="nav-link px-2 text-white-50">{% trans "Розклад" %}</a></li>
                <li><a href="{% url 'cms:cinemas_list' %}" class="nav-link px-2 text-white-50">{% trans "Кінотеатри" %}</a></li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle px-2 text-white-50" href="#" id="aboutDropdown" role="button"
                       data-toggle="dropdown" aria-expanded="false">
                        {% trans "Про нас" %}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="aboutDropdown">
                        <li><a class="dropdown-item" href="{% url 'main:news_page' %}">{% trans "Новини" %}</a></li>
                        <li><a class="dropdown-item" href="{% url 'cms:contacts_list' %}">{% trans "Контакти" %}</a></li>
                        {% for page in pages %}
                        <li><a class="dropdown-item" href="{% url 'main:page' page.id %}">{{ page.title }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
        </div>

        <div class="d-flex align-items-center">

        {% if request.user.is_superuser %}
            <div class="me-4 text-end">
                <a class="btn btn-primary" href="{% url 'adminlte:statistics' %}">Адмін панель</a>
            </div>
        {% endif %}

            <div class="me-4 text-end">
                <div>{{ phone1 }}</div>
                <div>{{ phone2 }}</div>
            </div>

            <div class="dropdown me-4">
                <a class="nav-link dropdown-toggle text-white text-uppercase" href="#" data-toggle="dropdown">
                    {{ CURRENT_LANG }}
                </a>

                <ul class="dropdown-menu dropdown-menu-dark">
                    {% get_available_languages as LANGUAGES %}
                    {% for lang_code, lang_name in LANGUAGES %}
                    <li>
                        <form action="{% url 'set_language' %}" method="post">
                            {% csrf_token %}
                            <input name="next" type="hidden" value="{{ request.get_full_path }}">
                            <input name="language" type="hidden" value="{{ lang_code }}">

                            <button type="submit" class="dropdown-item {% if lang_code == CURRENT_LANG %}active{% endif %}">
                                {{ lang_code|upper }}
                            </button>
                        </form>
                    </li>
                    {% endfor %}
                </ul>
            </div>

            <form class="me-3" role="search">
                <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="{% trans 'Пошук...' %}" aria-label="Search">
            </form>

            {% if request.user.is_authenticated %}
            <a href="{% url 'authentication:profile' %}" class="link-dark me-3">
                <i class="bi bi-person-bounding-box" style="font-size: 1.7rem; color: #6f42c1;"></i>
            </a>

            <a href="{% url 'authentication:logout' %}" class="link-danger">
                <i class="bi bi-box-arrow-right" style="font-size: 1.7rem;"></i>
            </a>

            {% else %}
            <a href="{% url 'authentication:login' %}" class="btn btn-outline-light me-2">{% trans "Увійти" %}</a>
            <a href="{% url 'authentication:register' %}" class="btn btn-warning">{% trans "Реєстрація" %}</a>
            {% endif %}

        </div>
    </header>

    {% block content %}{% endblock %}

    <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                    <img src="{% static 'img/logo.png' %}" width="30" height="30" alt="logo">
                </a>
                <span class="mb-3 mb-md-0 text-body-secondary">© 2026 Company, Inc</span>
            </div>

            <div class="col mb-3">
                <h5>{% trans "Афіша" %}</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2">
                        <a href="{% url 'main:schedule_page' %}" class="nav-link p-0 text-body-secondary">{% trans "Розклад" %}</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="{% url 'main:poster_coming_soon' %}" class="nav-link p-0 text-body-secondary">{% trans "Скоро в прокаті" %}</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="{% url 'cms:cinemas_list' %}" class="nav-link p-0 text-body-secondary">{% trans "Кінотеатри" %}</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="{% url 'main:actions_page' %}" class="nav-link p-0 text-body-secondary">{% trans "Акції" %}</a>
                    </li>
                </ul>
            </div>

            <div class="col mb-3">
                <h5>{% trans "Про кінотеатр" %}</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2">
                        <a href="{% url 'main:news_page' %}" class="nav-link p-0 text-body-secondary">{% trans "Новини" %}</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-body-secondary">{% trans "Реклама" %}</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="{% url 'main:page' 2 %}" class="nav-link p-0 text-body-secondary">{% trans "Кафе-Бар" %}</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-body-secondary">{% trans "Контакти" %}</a>
                    </li>
                </ul>
            </div>

            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <li class="ms-3">
                    <a class="text-body-secondary" href="#"><img src="{% static 'img/logo_facebook.jpg' %}" width="30" height="30" alt="Facebook"></a>
                </li>
                <li class="ms-3">
                    <a class="text-body-secondary" href="#"><img src="{% static 'img/logo_inst.jpg' %}" width="30" height="30" alt="Instagram"></a>
                </li>
            </ul>
        </footer>
    </div>

    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/color-modes.js' %}"></script>
</body>

</html>